site_name: PyLinkAndTrack
repo_url: https://github.com/Diaszano/pylinkandtrack
repo_name: Diaszano/pylinkandtrack
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/urso.png
  favicon: assets/urso.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [linkandtrack]